#!/usr/bin/env php
<?php

use Symfony\Component\Console\Command;
use Symfony\Component\Console\Input;
use Symfony\Component\Console\Output;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';



$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';
$kernel = new AppKernel($env, $debug);



if ($debug) {
    Debug::enable();
} else {

    $client = new \Raygun4php\RaygunClient($kernel->getContainer()->getParameter('raygun_apikey'));

    set_error_handler(function($errno, $errstr, $errfile, $errline) use ($client) {
        $client->SendError($errno, $errstr, $errfile, $errline);
    });
    set_exception_handler(function($exception) use ($client) {
        $client->SendException($exception);
    });
}


$application = new Application($kernel);
$application->register('test:raygun')
    ->setCode(function(Input\InputInterface $input, Output\OutputInterface $output) {
        user_error('User error message');
        throw new \Exception('Exception message', 666);
    });


$application->run($input);
